name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8
    - name: Build
      run: mvn package --file pom.xml
    - name: Test
      run: mvn test --file pom.xml
    - name: Upload coverage to Codecov
      uses: actions/codecov-action@v1.0.0
      with:
        token: ${{secrets.CODECOV_TOKEN}}
